version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - "5432:${DB_PORT}"
  app:
    links:
      - "db:${DB_HOST}"
    env_file:
      - .env
    build: .
    ports:
      - "${EVENT_PORT}:${EVENT_PORT}"
    restart: always

