version: "3"

services:
  db:
    image: postgres
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
  app:
    links:
      - "db:db"
    env_file:
      - .env
    build: .
    ports:
      - "${EVENT_PORT}:${EVENT_PORT}"

